name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/taleen911/project2

jobs:
  build-and-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u taleen911 --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Scan Image
        run: docker images

      - name: Deploy Container
        run: |
          docker rm -f skillmatch-app || true
          docker run -d --name skillmatch-app -p 5000:5000 $IMAGE_NAME:latest

      - name: Verify Deployment
        run: docker ps
