name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/taleen911/project2

jobs:
  build-and-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u taleen911 --password-stdin

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Scan Image
        run: |
          docker images

  build-and-deploy:
    needs: build-and-scan
    runs-on: self-hosted

    steps:
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u taleen911 --password-stdin

      - name: Pull Latest Image
        run: |
          docker pull $IMAGE_NAME:latest

      - name: Deploy
        run: |
          cd /home/aau/Desktop/Skills_Utilization
          docker compose down
          ./vault.sh
          docker compose up -d
