name: Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: |
          python3 -m pip install --break-system-packages bandit

      - name: Run Bandit
        continue-on-error: true
        run: |
          bandit -r . -f txt -o bandit-report.txt || true

      - name: Run Hadolint
        continue-on-error: true
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile > hadolint-report.txt || true

      - name: Run TruffleHog
        continue-on-error: true
        run: |
          docker run --rm \
            -v "$PWD:/work" \
            ghcr.io/trufflesecurity/trufflehog:latest filesystem /work \
            > trufflehog-report.txt || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.txt
            hadolint-report.txt
            trufflehog-report.txt
