name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Secrets From Vault
        run: |
          chmod +x vault.sh
          ./vault.sh

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/taleen911/project2:latest

      - name: Secret Detection
        run: |
          grep -R -i "password\|secret\|token" . || true

      - name: Verify
        run: |
          echo "Security scan completed"
